import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
# print(arr)
# print(np.shape(arr))
# print(np.size(arr))
# print(np.ndim(arr))
a = np.array([1, 5, 5], dtype=float)
# print(a.dtype)
a = np.array([[1, 2, 3], [4, 5, 6]])
a = np.zeros((3, 4))
a = np.ones((3, 4))
a = np.empty((3, 4))
a = np.arange(10, 20, 2)
a = np.arange(12).reshape((3, 4))
a = np.linspace(1, 10, 6).reshape(2, 3)
# print(a)
